---
title: "Figure 2a - Tumor and Cell lines SE signal heatmap"
author: "Health Data Science Unit"
date: "`r date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    number_sections: false
params:
  annot_tumor : "path/to/metadata"
  annot_cells : "path/to/metadata"
  se_signal   : "path/to/data"
  figure      : "results/figures/..."
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
#this chunk sets global options for Rmarkdown
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")


library(ComplexHeatmap)
library(tidyverse)
library(viridis)


```


## Data loading
  
  
```{r dataloading}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                             Read Data                                      ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
# Read matrix
quantnorm.matrix <- readRDS(params$se_signal)

# read annotation 
annot_tumor <- readRDS(params$annot_tumor)
annot_cells <- readRDS(params$annot_cells)

annot <- bind_rows(annot_tumor, annot_cells)
annot <- annot[annot$avail.ChIPseq, ]
head(annot)


```

  

```{r Clustering}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                                Clustering                                  ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##

colnames(quantnorm.matrix)

# perform column clustering to use in heatmap
transdist_matrix <- dist(t(quantnorm.matrix))
transclust_matrix <- hclust(transdist_matrix, method="ward.D2") 

# perform k-means clustering for SE in rows and first find optimal center number (elbow method)
wss <- (nrow(quantnorm.matrix)-1)*sum(apply(quantnorm.matrix,2,var))
for (i in 2:50) wss[i] = sum(kmeans(quantnorm.matrix,centers=i, iter.max=30)$withinss)
#plot(1:50, wss, type="b", xlab="Number of Clusters",ylab="Within groups sum of squares")
k = kmeans(quantnorm.matrix, centers=10, iter.max=30)

# for changing row order of matrix according to clusters
row_annotation_sort = data.frame(#TSS=as.factor(MERGEDSE$TSS), Length=length.bins, 
  Cluster=k$cluster)
row_ann_clust_sorted = row_annotation_sort[order(row_annotation_sort$Cluster),,drop=FALSE]
row_ann_clust_sorted$Cluster =as.factor(row_ann_clust_sorted$Cluster)
quantnorm.df = as.data.frame(quantnorm.matrix)
quantnorm.df_clust_sorted = quantnorm.df[match(rownames(row_ann_clust_sorted), rownames(quantnorm.df)),]
quantnorm.matrix_clust_sorted = as.matrix(quantnorm.df_clust_sorted)





```

```{r heatmap}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        H matrix heatmap annotation                         ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
#Annotation for H matrix heatmap
type.colVector <- list(Type    = c("Tumor"="grey80", "Metastasis"="grey60", "Cell line"="grey20", "NA"="white"),
                       MYCN    = c("Amp"="grey20", "NonAmp"="grey80", "NA"="white"),
                       Stage   = c("4"="grey20", "1-3;4S"="grey80", "NA"="white"),
                       Age     = c(">18mo"="grey20", "<18mo"="grey80", "NA"="white"),
                       Relapse = c("Yes"="grey20", "No"="grey80", "NA"="grey100"))

#Heatmap annotation
heat.anno <- HeatmapAnnotation(df = data.frame(Type    = annot$Type,
                                               MYCN    = annot$MYCN,
                                               Stage   = annot$Stage,
                                               Age     = annot$Age,
                                               Relapse = annot$Relapse),
                               col = type.colVector,
                               show_annotation_name = TRUE, na_col = "white")


darkpercent <- 10
colscheme <- c(viridis(n=darkpercent, begin=0, end=0.5, option="viridis"), 
               viridis(n=100-darkpercent, begin=0.5, end=1, option="viridis")[-1])


##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                                   Heatmap                                  ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##

se.heatmap <- Heatmap(quantnorm.matrix_clust_sorted,
                      col = colscheme,
                      name = "SE Signal",
                      cluster_columns = transclust_matrix,
                      heatmap_legend_param = 
                        list(color_bar = "continuous", legend_height=unit(2, "cm")),
                      show_column_names = TRUE,
                      show_row_names = FALSE,
                      cluster_rows = FALSE,
                      top_annotation = heat.anno)
se.heatmap


pdf(params$figure, width = 16, height = 7, paper = "special")
se.heatmap
dev.off()


```
