---
title: "Sup. Figure 2e - Tumor Most Variable Genes RNAseq NMF"
author: "Health Data Science Unit"
date: "`r date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    number_sections: false
params:
  K         : 4
  annot     : "annotation/annotation_tumor.RDS"
  norm_nmfW : "analysis/tumor/rnaseq/NMF_mostVariable/tumor_mostVariable_normNMF_W.RDS"
  norm_nmfH : "analysis/tumor/rnaseq/NMF_mostVariable/tumor_mostVariable_normNMF_H.RDS"
  hmatrix_wnorm : "path/to/..."
  wmatrix_wnorm : "path/to/..."
  nmf_features  : "path/to/..."
  hmatrix_hnorm : "analysis/tumor/rnaseq/NMF_mostVariable/tumor_mostVariable_K4_Hmatrix_hnorm.RDS"
  sup_figure2e  : "results/figures..."
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
#this chunk sets global options for Rmarkdown
knitr::opts_chunk$set(echo = TRUE)
#setting working directory. Should be home directory of the project
options(knitr.table.format="html")

library(Bratwurst)
library(viridis)
library(ComplexHeatmap)
library(circlize)
library(ggplot2)
library(knitr)

```


## Data loading
  

```{r dataloading}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                          Read NMF objects                                  ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
# read W normalized NMF
norm.nmf.exp <- readRDS(params$norm_nmfW)
# read H normalized NMF
norm.nmf.exp.H <- readRDS(params$norm_nmfH)

# read annotation 
annot <- readRDS(params$annot)
annot <- annot[match(colnames(norm.nmf.exp), annot$ProjectID),]
rownames(annot) <- annot$ProjectID



```



```{r H_IDs}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        Assign Signature Names                              ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
signature_idx <- 1:params$K
names(signature_idx) <- paste0("Sign.", signature_idx)

```


### Save NMF objects


```{r saveNMFobjects}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##               Select opt K and compute feature stats                     ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
K <- params$K
norm.nmf.exp <- setOptK(norm.nmf.exp, K)
norm.nmf.exp@OptK

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                             NMH H Matrix                                 ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
norm.nmf.hmatrix <- HMatrix(norm.nmf.exp, k = K)[signature_idx,]
colnames(norm.nmf.hmatrix) <- colnames(norm.nmf.exp)
rownames(norm.nmf.hmatrix) <- names(signature_idx)
saveRDS(norm.nmf.hmatrix, params$hmatrix_wnorm)

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                             NMH W Matrix                                 ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
norm.nmf.wmatrix <- WMatrix(norm.nmf.exp, k = K)[,signature_idx]
colnames(norm.nmf.wmatrix) <- names(signature_idx)
rownames(norm.nmf.wmatrix) <- rownames(norm.nmf.exp)
saveRDS(norm.nmf.wmatrix, params$wmatrix_wnorm)

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                      NMF Signature features                              ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
norm.nmf.exp <- computeFeatureStats(norm.nmf.exp)
norm.nmf.exp <- computeSignatureSpecificFeatures(norm.nmf.exp, 1)
SignaFeat <- do.call(cbind, lapply(1:norm.nmf.exp@OptK, function(i){
  as.numeric(substr(norm.nmf.exp@FeatureStats$cluster, i, i))
}))
SignaFeat <- as.data.frame(SignaFeat)[,signature_idx]
#rownames are features names
rownames(SignaFeat) <- rownames(norm.nmf.exp)
#colnames are signatures
colnames(SignaFeat) <- names(signature_idx)
saveRDS(SignaFeat, params$nmf_features)


```


```{r saveNMFobjectsHnorm}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                             NMH H Matrix                                 ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
norm.nmf.hmatrix.hnorm <- HMatrix(norm.nmf.exp.H, k = K)[signature_idx,]
colnames(norm.nmf.hmatrix.hnorm) <- colnames(norm.nmf.exp.H)
rownames(norm.nmf.hmatrix.hnorm) <- names(signature_idx)
saveRDS(norm.nmf.hmatrix.hnorm, params$hmatrix_hnorm)

```


### H Matrix, W normalized: 
  
  
```{r Hmatrix_Wnorm, fig.width=10, fig.height=5.5, out.width="90%"}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        H matrix heatmap annotation                         ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
#Annotation for H matrix heatmap
type.colVector <- list(Type    = c("Tumor"="grey80", "Metastasis"="grey60", "NA"="white"),
                       MYCN    = c("Amp"="grey20", "NonAmp"="grey80", "NA"="white"),
                       Stage   = c("4"="grey20", "1-3;4S"="grey80", "NA"="white"),
                       Age     = c(">18mo"="grey20", "<18mo"="grey80", "NA"="white"),
                       Relapse = c("Yes"="grey20", "No"="grey80", "NA"="grey100"))

#Heatmap annotation
heat.anno <- HeatmapAnnotation(df = data.frame(Type    = annot$Type,
                                               MYCN    = annot$MYCN,
                                               Stage   = annot$Stage,
                                               Age     = annot$Age,
                                               Relapse = annot$Relapse),
                               col = type.colVector,
                               show_annotation_name = TRUE, na_col = "white")


##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##              Generate H matrix heatmap, W normalized                       ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
#plot H matrix
h.heatmap <- Heatmap(norm.nmf.hmatrix,
                     col  = inferno(n=100),
                     name = "Exposure",
                     clustering_distance_columns = 'pearson',
                     show_column_dend = FALSE,
                     heatmap_legend_param = 
                       list(color_bar = "continuous", legend_height=unit(2, "cm")),
                     top_annotation = heat.anno,
                     show_column_names = FALSE,
                     show_row_names = FALSE,
                     cluster_rows = FALSE)
print(h.heatmap)

#save H matrix heatmap
pdf(file = params$sup_figure2e, width=10, height=7)
h.heatmap
dev.off()


```


