---
title: "Figure 2a - Tumor and Cell lines SE signal heatmap"
author: "Health Data Science Unit"
date: "`r date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    number_sections: false
params:
  matrix    : "analysis/tumor/rnaseq/exprs/tumor_RNAseq_TPM_Matrix_filt_log.RDS"
  SE        : "analysis/tumor/SE_annot/tumor_consensusSE_target_GRanges.RDS"
  metadata  : "path/to/..."
  
  
  annot_tumor : "annotation/annotation_tumor.RDS"
  annot_cells : "path/to/metadata"
  se_signal   : "path/to/data"
  figure      : "results/sup_figure2/SE_target_and_mostVariable_heatmap_clustering.pdf"
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
#this chunk sets global options for Rmarkdown
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")


library(ComplexHeatmap)
library(tidyverse)
library(viridis)


```


## Data loading
  
  
```{r dataloading}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                             Read Data                                      ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
# read normalized matrix
norm.mat <- readRDS(params$matrix)
# read annotation 
annot <- readRDS(params$annot_tumor)
annot  <- annot[match(colnames(norm.mat), annot$ProjectID),]

# Read SE Granges
SE <- readRDS(params$SE)

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##           Filter matrix to keep only most variable geness                  ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
rownames(norm.mat) <- sapply(strsplit(rownames(norm.mat), "\\|"), "[[", 1)

# number of genes equal to the number of SE target genes
ntop <- length(unique(SE$target_ENSEMBL))
# Find most variable genes
rv <- rowVars(norm.mat)
select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, length(rv)))]
# norm.mat <- norm.mat[select,]


tmp.dim <- data.frame(dim(norm.mat))
colnames(tmp.dim) <- "Value"
cat("Dimension of input Matrix  \n  ") 
kable(tmp.dim) 


##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                     Assign NMF expusre to annot                            ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
htumor <- readRDS("analysis/tumor/rnaseq/NMF/tumor_consensusSE_K4_Hmatrix_hnorm.RDS")
#htumor <- readRDS("analysis/tumor/rnaseq/NMF/tumor_consensusSE_K4_Hmatrix_wnorm.RDS")
h_sig_assign <- apply(htumor, 2, function(x) names(x)[which.max(x)])
annot$NMF_sign <- h_sig_assign[match(annot$ProjectID, names(h_sig_assign))]

annot <- as.data.frame(t(htumor)) %>% 
  setNames(paste0('NMF_', names(.))) %>% 
  rownames_to_column("ProjectID") %>% 
  left_join(annot, by = "ProjectID")

head(annot)

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                      Z score transform                                     ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
zScore_matrix <- function(x) {
  zvector <- function(num) {
    #mean_ad <- 1.253314*mean(abs(num - mean(num)))
    #(num - median(num)) / mean_ad
    
    #(num - median(num)) / mad(num)
    (num - mean(num)) / sd(num)
    
  }
  x_z <- t(apply(x, MARGIN=1, zvector))
  x_z <- apply(x_z, MARGIN=2, zvector)
  
  #x_z <- apply(x, MARGIN=2, zvector)
  #x_z <- t(apply(x_z, MARGIN=1, zvector))
  x_z
}

norm_mat_z <- zScore_matrix(norm.mat)
norm_mat_z[1:5,1:5]
min(norm_mat_z)
max(norm_mat_z)

norm_mat_SE_target <- norm_mat_z[unique(SE$target_ENSEMBL),]
min(norm_mat_SE_target);max(norm_mat_SE_target)
#norm_mat_SE_target <- norm.mat[unique(SE$target_ENSEMBL),]
# dim(norm_mat_SE_target)

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##           Filter matrix to keep only most variable geness                  ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##

# number of genes equal to the number of SE target genes
ntop <- length(unique(SE$target_ENSEMBL))
# Find most variable genes
rv <- rowVars(norm_mat_z)
select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, length(rv)))]
norm_mat_mostvar <- norm_mat_z[select,]
min(norm_mat_mostvar);max(norm_mat_mostvar)

#norm_mat_SE_target <- norm.mat[unique(SE$target_ENSEMBL),]
# dim(norm_mat_SE_target)

hist(norm_mat_mostvar)

```

```{r heatmap}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        H matrix heatmap annotation                         ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
colscale_quant <- function(x, prob = 0.01) {
  circlize::colorRamp2(seq(quantile(x, probs = prob), 
                           quantile(x, probs = 1-prob), 
                           length.out = 100), 
                       viridis(100))
}


#Annotation for H matrix heatmap
type.colVector <- list(Type    = c("Tumor"="grey80", "Metastasis"="grey60", "Cell line"="grey20", "NA"="white"),
                       MYCN    = c("Amp"="grey20", "NonAmp"="grey80", "NA"="white"),
                       Stage   = c("4"="grey20", "1-3;4S"="grey80", "NA"="white"),
                       Age     = c(">18mo"="grey20", "<18mo"="grey80", "NA"="white"),
                       Relapse = c("Yes"="grey20", "No"="grey80", "NA"="grey100"),
                       NMF_MYCN= colscale_quant(annot$NMF_MYCN,prob = 0.0), 
                       NMF_MES = colscale_quant(annot$NMF_MES, prob = 0.0), 
                       `NMF_MNA-LR` = colscale_quant(annot$`NMF_MNA-LR`, prob = 0.0),
                       `NMF_MNA-HR` = colscale_quant(annot$`NMF_MNA-HR`, prob = 0.0),
                       NMF_sign= setNames(inferno(length(unique(annot$NMF_sign))), unique(annot$NMF_sign)))

#Heatmap annotation
heat.anno <- HeatmapAnnotation(df = data.frame(Type    = annot$Type,
                                               MYCN    = annot$MYCN,
                                               Stage   = annot$Stage,
                                               Age     = annot$Age,
                                               Relapse = annot$Relapse,
                                               NMF_MYCN= annot$NMF_MYCN,
                                               NMF_MES = annot$NMF_MES,
                                               `NMF_MNA-LR` = annot$`NMF_MNA-LR`,
                                               `NMF_MNA-HR` = annot$`NMF_MNA-HR`,
                                               NMF_sign= annot$NMF_sign, 
                                               check.names = FALSE),
                               col = type.colVector,
                               show_annotation_name = TRUE, na_col = "white")



```




```{r setarget}



hist(norm_mat_SE_target)
Heatmap(norm_mat_SE_target,
        #col = viridis(100),
        col = colscale_quant(norm_mat_SE_target, prob = 0.01),
        name = "SE target expression",
        #cluster_columns = transclust_matrix,
        #heatmap_legend_param = 
        #list(color_bar = "continuous", legend_height=unit(2, "cm")),
        show_column_names = FALSE,
        show_row_names = FALSE,
        show_row_dend = FALSE,
        cluster_rows = TRUE,
        use_raster = TRUE,
        raster_quality = 1,
        top_annotation = heat.anno)

```

```{r mostvar}

Heatmap(norm_mat_mostvar,
        col = colscale_quant(norm_mat_mostvar, prob = 0.01),
        name = "Most variable expression",
        #cluster_columns = transclust_matrix,
        #heatmap_legend_param = 
        #list(color_bar = "continuous", legend_height=unit(2, "cm")),
        show_column_names = FALSE,
        show_row_names = FALSE,
        cluster_rows = TRUE, 
        show_row_dend = FALSE,
        use_raster = TRUE,
        raster_quality = 1,
        top_annotation = heat.anno)
```


  

```{r Clustering}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                                Clustering                                  ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##




cluster_and_heat <- function(x, col_quant = 0.01, centers = 10, name = "heat", raster_quality = 1) {
  colnames(x)
  
  # perform column clustering to use in heatmap
  transdist_matrix <- dist(t(x))
  transclust_matrix <- hclust(transdist_matrix, method="ward.D2") 
  #k <- kmeans(x, centers=10, iter.max=30)
  k <- kmeans(x, centers=centers, iter.max=30)
  
  # for changing row order of matrix according to clusters
  k_cluster_sorted <- sort(k$cluster)
  #print(k$cluster)
  #print(k_cluster_sorted)
  x_clust_sorted <- x[names(k_cluster_sorted),]
  x_annot <- annot[match(colnames(x_clust_sorted), annot$ProjectID),]
  
  ##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
  ##                                 Heatmap                                  ##
  ##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
  Heatmap(x_clust_sorted,
          col               = colscale_quant(x_clust_sorted, prob = col_quant),
          name              = name,
          column_title      = name,
          cluster_columns   = transclust_matrix,
          show_column_names = FALSE,
          show_row_names    = FALSE,
          cluster_rows      = FALSE,
          use_raster        = TRUE,
          raster_quality    = raster_quality,
          top_annotation    = heat.anno)
  
}


heat_list <- cluster_and_heat(norm_mat_SE_target, col_quant = 0.05, centers = 10, name = "SE targets exprs", raster_quality = 10) +
  cluster_and_heat(norm_mat_mostvar,  col_quant = 0.05, centers = 10, name = "Most variable exprs", raster_quality = 10)


draw(heat_list, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")



pdf(params$figure, width = 10, height = 10, paper = "special")

draw(heat_list, heatmap_legend_side = "bottom", annotation_legend_side = "bottom", auto_adjust = FALSE)
#draw(heat_list, heatmap_legend_side = "bottom", annotation_legend_side = "bottom", padding = unit(c(2, 100, 2, 2), "mm"))
#heat_list
dev.off()


```
