---
title: "Figure 2b"
author: "Health Data Science Unit"
date: "`r date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    number_sections: false
params:
  annot_tumor   : "annotation/annotation_tumor.RDS"
  annot_cells   : "annotation/annotation_cells.RDS"
  SE_signal        : "analysis/tumor_cells/chipseq/H3K27ac/consensusSE/tumor_cells_H3K27ac_noH3K4me3_consensusSE_SignalScore.RDS"
  hmatrix_wnorm : "analysis/tumor_cells/chipseq/H3K27ac/NMF/tumor_cells_consensusSE_K5_Hmatrix_wnorm.RDS"
  figure2c      : "results/figures/figure2/..."
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
#this chunk sets global options for Rmarkdown
knitr::opts_chunk$set(echo = TRUE)
#setting working directory. Should be home directory of the project
knitr::opts_knit$set(root.dir=params$work_dir)
options(knitr.table.format="html")


library(ComplexHeatmap)

library(umap)
library(tidyverse)
library(ggrepel)
library(viridis)
library(writexl)

```

# Figure 2.a Cell lines SE signal NMF H matrix

## Data loading
  
Read NMF object
  
```{r dataloading}

# params <- list(annot_tumor = "annotation/annotation_tumor.RDS",
#                annot_cells = "annotation/annotation_cells.RDS",
#                SE_signal   = "analysis/tumor_cells/chipseq/H3K27ac/consensusSE/tumor_cells_H3K27ac_noH3K4me3_consensusSE_SignalScore.RDS",
#                hmatrix_wnorm = "analysis/tumor_cells/chipseq/H3K27ac/NMF/tumor_cells_consensusSE_K5_Hmatrix_wnorm.RDS")


##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                             Read SE signal                                 ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
se_signal <- readRDS(params$SE_signal)

# read annotation 
annot_tumor <- readRDS(params$annot_tumor)
annot_cells <- readRDS(params$annot_cells)

annot <- bind_rows(annot_tumor, annot_cells)
annot <- annot[annot$avail.ChIPseq, ]
annot$Type[annot$Type == "Metastasis"] <- "Tumor"

head(annot)

# Read NMF H matrix
hmatrix <- readRDS(params$hmatrix_wnorm)

```

```{r hmat_heatmap}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        H matrix heatmap annotation                         ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
#Annotation for H matrix heatmap
type.colVector <- list(Type    = c("Tumor"="grey80", "Metastasis"="grey60", "Cell line"="grey20", "NA"="white"),
                       MYCN    = c("Amp"="grey20", "NonAmp"="grey80", "NA"="white"),
                       Stage   = c("4"="grey20", "1-3;4S"="grey80", "NA"="white"),
                       Age     = c(">18mo"="grey20", "<18mo"="grey80", "NA"="white"),
                       Relapse = c("Yes"="grey20", "No"="grey80", "NA"="grey100"))

#Heatmap annotation
heat.anno <- HeatmapAnnotation(df = data.frame(Type    = annot$Type,
                                               MYCN    = annot$MYCN,
                                               Stage   = annot$Stage,
                                               Age     = annot$Age,
                                               Relapse = annot$Relapse),
                               col = type.colVector,
                               show_annotation_name = TRUE, na_col = "white")


##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##              Generate H matrix heatmap, W normalized                       ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
#plot H matrix
h.heatmap <- Heatmap(hmatrix,
                     col  = viridis(n=100),
                     name = "Exposure",
                     clustering_distance_columns = 'pearson',
                     show_column_dend = FALSE,
                     heatmap_legend_param = 
                       list(color_bar = "continuous", legend_height=unit(2, "cm")),
                     top_annotation = heat.anno,
                     show_column_names = TRUE,
                     show_row_names = FALSE,
                     cluster_rows = FALSE)
print(h.heatmap)

```


```{r run_UMAP}


##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                                 run UMAP                                   ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
# Run umap with default params
#set.seed(52)
set.seed(14)
#set.seed(20)
chip_umap <- umap(t(se_signal))
plot(chip_umap$layout)

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        Annotation to plot                                  ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##


chip_umap_df <- as.data.frame(chip_umap$layout)
colnames(chip_umap_df) <- c("UMAP1", "UMAP2")
head(chip_umap_df)

chip_umap_df$ProjectID <- rownames(chip_umap_df)
chip_umap_df$Type <- annot$Type[match(chip_umap_df$ProjectID, annot$ProjectID)]
chip_umap_df$MYCN <- annot$MYCN[match(chip_umap_df$ProjectID, annot$ProjectID)]
chip_umap_df$MYCN <- ifelse(chip_umap_df$MYCN == "Amp", "MYCN", "MNA")
chip_umap_df$Class <- paste0(chip_umap_df$Type, "-", chip_umap_df$MYCN)

##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        Include MES exposure                                ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
hmatrix_zscores <- t(apply(hmatrix, MARGIN=1, function(exposure){
  (exposure - median(exposure)) / mad(exposure)
}))

MES_score <- hmatrix_zscores[which.max(hmatrix_zscores[,"P5"]),]

# MES_score <- hmatrix[which.max(hmatrix[,"P5"]),]
# MES_score <- (MES_score*10)/max(MES_score)

MES_score <- hmatrix[which.max(hmatrix[,"P5"]),]
MES_score <- log2(round(MES_score,2)+1)
MES_score[MES_score<0] = -3
  
# assign MES score
chip_umap_df$MES_score <- MES_score[match(chip_umap_df$ProjectID, names(MES_score))]
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        plot UMAP                                           ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                           basic ggplot theme                               ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
tm <- theme_bw() +
  theme(#axis.line=element_line(colour = "black"),
    #axis.line = element_line(size = .1, colour = "grey20"),
    legend.text = element_text(size=5),
    #axis.line=element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    #panel.border = element_blank(),
    panel.background = element_blank())


gg_umap <- ggplot(chip_umap_df, aes(x=UMAP1, y=UMAP2, color = MES_score)) + 
  #theme_bw() + 
  geom_point(aes(shape=Class),size=3) + 
  scale_shape_manual(values=c(15:20))+ 
  scale_colour_viridis(name = paste("MES","Score",sep="\n")) +
  # geom_text_repel(data = dplyr::filter(chip_umap_df, Type=="Cell line" & MES_score > 5), 
  #                 mapping = aes(label=ProjectID), size=3, color = "Black") +
  geom_text_repel(data = dplyr::filter(chip_umap_df, Type=="Cell line" & MES_score > 9.5), 
                  mapping = aes(label=ProjectID), size=3, color = "Black") +
  tm
  # geom_text_repel(data = dplyr::filter(chip_umap_df, 
  #                                    Type=="Cell line" &
  #                                      UMAP1 > 0 & UMAP2 > 2), 
  #                 mapping = aes(label=ProjectID),size=3)
gg_umap

write_xlsx(list(`Figure 2c`= gg_umap$data), 
           path = "results/figure_source_data/Figure_2c.xlsx")


ggsave(filename = params$figure2c, 
       plot = gg_umap, width = 4, height = 3)


```

