---
title: "Tumors RNAseq NMF Primary vs Relapse pairs"
author: "Health Data Science Unit"
date: "`r date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    number_sections: false
params:
  work_dir : "/icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/"
  tumor_h  : "/icgc/dkfzlsdf/analysis/B080/crg/B087_Neuroblastoma/publication_GEO/analysis/tumor/rnaseq/NMF/tumor_consensusSE_K4_Hmatrix_wnorm.RDS"
  figure   : "results/figure4/tumors_RNAseq_PrimaryVsRelapse.pdf"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#this chunk sets global options for Rmarkdown
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")

library(viridis)
library(ComplexHeatmap)
library(ggplot2)
library(knitr)
library(kableExtra)
library(ggradar)
library(patchwork)

```

# Tumors RNAseq NMF H matrix  
  
```{r NMF_HMatrix, , fig.width=10, fig.height=5.5, out.width="90%"}
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
##                        Read NMF H matrix data                              ##
##––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––##
tumors.nmf.hmatrix <- readRDS(params$tumor_h)


```

# Primary vs Relapse radar plots

```{r PrimaryVsRelapse_ggradar, message=FALSE, results='asis'}
# Helper function
signatureRadar <- function(sampleID, hmatrix){
  # Find Primary samples and relapse IDs
  nspIDs <- grep(sampleID, colnames(hmatrix), value = TRUE)
  annot <- data.frame(ProjectID = nspIDs,
                      type      = factor(substr(nspIDs, start = 8, stop = 9), 
                                         levels = c("PT", "RT", "RM")),
                      stringsAsFactors = FALSE)
  
  print(annot)
  # Assign color
  group.colours <- c(PT = "#2FB47CFF", RT = "#420A68FF", RM = "#F76F5CFF")
  group.colours <- group.colours[match(annot$type, names(group.colours))]
  names(group.colours) <- annot$ProjectID
  
  # format dataframe to radar plots
  scores <- hmatrix[,annot$ProjectID,drop=FALSE]
  maxScale <- max(scores)
  
  scores <- cbind(colnames(scores), as.data.frame(t(scores)))
  print(scores)
  ggradar(scores, grid.max=maxScale, grid.mid=maxScale/2,
          font.radar="Helvetica",
          grid.label.size = 1,
          axis.label.size = 1,
          group.point.size = .5, 
          group.line.width = 0.5,
          group.colours = group.colours, 
          background.circle.transparency = 1,
          legend.text.size = 4,
          gridline.min.linetype = "solid",
          gridline.mid.linetype = "solid",
          gridline.max.linetype = "solid",
          background.circle.colour = NA,
          gridline.min.colour = "grey60",
          gridline.mid.colour = "grey40",
          gridline.max.colour = "grey20",
          axis.line.colour = "firebrick",
          grid.line.width = .5)
}




sampleIDs <- c("NSP032", "NSP090", "NSP460")
names(sampleIDs) <- sampleIDs




radars <-  
  signatureRadar("NSP032", tumors.nmf.hmatrix) +
  signatureRadar("NSP090", tumors.nmf.hmatrix) +
  signatureRadar("NSP460", tumors.nmf.hmatrix) +
  plot_layout(ncol = 1, heights = c(4, 4, 4))

radars

ggsave(filename = params$figure, radars, width = 3, height = 4)


```

```{r}
library(tidyverse)
# Helper function
signatureExposure <- function(sampleID, hmatrix){
  # Find Primary samples and relapse IDs
  nspIDs <- grep(sampleID, colnames(hmatrix), value = TRUE)
  annot <- data.frame(ProjectID = nspIDs,
                      type      = factor(substr(nspIDs, start = 8, stop = 9), 
                                         levels = c("PT", "RT", "RM")),
                      stringsAsFactors = FALSE)
  
  #print(annot)
  # Assign color
  #group.colours <- c(PT = "#2FB47CFF", RT = "#420A68FF", RM = "#F76F5CFF")
  #group.colours <- group.colours[match(annot$type, names(group.colours))]
  #names(group.colours) <- annot$ProjectID
  
  # format dataframe to radar plots
  scores <- hmatrix[,annot$ProjectID,drop=FALSE]
  maxScale <- max(scores)
  scores <- as.data.frame(t(scores)) %>% 
    rownames_to_column("ProjectID") %>% 
    mutate(patient_id = sampleID)
  left_join(scores, annot, "ProjectID") %>% 
    mutate(type = as.character(type)) %>% 
    mutate(type = if_else(type == "PT", "Primary", type)) %>% 
    mutate(type = if_else(type == "RT", "Relapse (primary site)", type)) %>% 
    mutate(type = if_else(type == "RM", "Relapse (metastatic site)", type)) %>% 
    mutate(type = factor(type, levels = c("Primary", "Relapse (primary site)", "Relapse (metastatic site)")))
  
  # scores <- cbind(colnames(scores), as.data.frame(t(scores)))
  # print(scores)
  
}

x <- bind_rows(lapply(sampleIDs, signatureExposure, tumors.nmf.hmatrix)) %>% 
  pivot_longer(-c("ProjectID", "patient_id", "type"), names_to = "Signature", values_to = "Exposure") %>% 
  #group_by(patient_id, Signature) %>% 
  group_by(patient_id) %>% 
  mutate(Exposure = Exposure/max(Exposure)) %>% 
  #ggplot(aes(x = ProjectID, y = Exposure, fill = Signature)) +
  ggplot(aes(x = ProjectID, y = Exposure, fill = type)) +
  geom_bar(stat = "identity") +
  #facet_grid(Signature~patient_id, scales = "free") +
  facet_grid(Signature~patient_id, scales = "free_x") +
  scale_fill_manual(values = c("#2FB47CFF", "#420A68FF", "#F76F5CFF")) +
  #facet_grid(patient_id~Signature, scales = "free") +
  theme_cowplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
x
ggsave(filename = "results/figure4/tumors_RNAseq_PrimaryVsRelapse_barplot.pdf", x, width = 7, height = 6)

```




```{r savetables}
# signatureRadar <- function(samples, hmatrix){
#   scores <- hmatrix[,samples]
#   maxScale <- max(scores)
#   rownames(scores) <- c("MYCN", "Mesenchymal", "MNA-LR", "MNA-HR")
#   scores <- as.data.frame(t(scores))
#   
#   idx <- match(rownames(scores), sampleannot_relapse$PatID)
#   rownames(scores) <- sampleannot_relapse$ProjectID[idx]
#   
#   # type of tumor
#   #scores$Sample_Type <- ifelse(is.na(sampleannot_relapse$Relapse[idx]), "Primary", "Relapse")
#   scores$Sample_Type <- sapply(sampleannot_relapse$INFORM[idx], function(infID){
#     ifelse(is.na(infID), "Primary", paste0("Relapse_", infID))
#   })
#   print(scores)
#   
#   write.csv(scores, paste0("publication/tables/Relapse_exposures", paste(rownames(scores), collapse = "_"), "NMF_hmatrix_tumors_RNAseq.csv"))
# }


```

